name: iOS Continuous Integration

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Show Xcode Version
        run: |
          xcodebuild -version

      - name: Show Available Simulators
        run: |
          xcrun simctl list devices available

      - name: Resolve Swift Packages
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project FillITheBlanksGame.xcodeproj

      - name: Show Destinations
        run: |
          xcodebuild \
            -project FillITheBlanksGame.xcodeproj \
            -scheme FillITheBlanksGame \
            -showdestinations

        - name: Install CocoaPods
        run: |
            pod install

      - name: Run Tests
        run: |
          xcodebuild test \
            -project FillITheBlanksGame.xcodeproj \
            -scheme FillITheBlanksGame \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -enableCodeCoverage YES
